//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClientGenerator.Generators.Marshallers {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class CborResponseUnmarshaller : BaseResponseUnmarshaller {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "CborResponseUnmarshaller.tt"

    AddLicenseHeader();

    AddCommonUsingStatements();

            
            #line default
            #line hidden
            
            #line 11 "CborResponseUnmarshaller.tt"
            this.Write("using Amazon.Util;\nusing System.Formats.Cbor;\nusing Amazon.Extensions.CborProtoco" +
                    "l.Internal.Transform;\n\n#pragma warning disable CS0612,CS0618\nnamespace ");
            
            #line default
            #line hidden
            
            #line 16 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Namespace ));
            
            #line default
            #line hidden
            
            #line 16 "CborResponseUnmarshaller.tt"
            this.Write(".Model.Internal.MarshallTransformations\n{\n    /// <summary>\n    /// Response Unma" +
                    "rshaller for ");
            
            #line default
            #line hidden
            
            #line 19 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 19 "CborResponseUnmarshaller.tt"
            this.Write(" operation\n    /// </summary>  \n    public class ");
            
            #line default
            #line hidden
            
            #line 21 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 21 "CborResponseUnmarshaller.tt"
            this.Write(@"ResponseUnmarshaller : CborResponseUnmarshaller
    {
        /// <summary>
        /// Unmarshaller the response from the service to the response class.
        /// </summary>  
        /// <param name=""context""></param>
        /// <returns></returns>
        public override AmazonWebServiceResponse Unmarshall(CborUnmarshallerContext context)
        {
            ");
            
            #line default
            #line hidden
            
            #line 30 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 30 "CborResponseUnmarshaller.tt"
            this.Write("Response response = new ");
            
            #line default
            #line hidden
            
            #line 30 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name ));
            
            #line default
            #line hidden
            
            #line 30 "CborResponseUnmarshaller.tt"
            this.Write("Response();\n            var reader = context.Reader;\n            context.AddPathS" +
                    "egment(\"");
            
            #line default
            #line hidden
            
            #line 32 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            
            #line 32 "CborResponseUnmarshaller.tt"
            this.Write("\");\n");
            
            #line default
            #line hidden
            
            #line 33 "CborResponseUnmarshaller.tt"

    var payload = this.Operation.ResponsePayloadMember;
    var unmarshallPayload = payload != null && payload.IsStructure;
    var payloadIsStream = payload != null && !unmarshallPayload;
    bool isEventStreamOutput = this.Operation.IsEventStreamOutput;
    if (this.Operation.ResponseHasBodyMembers || payload != null)
    {
        if (this.Operation.AllowEmptyResult)
        {
            throw new NotImplementedException("AllowEmptyResult is not implemented for JSON unmarshallers");
        }
        if (isEventStreamOutput)
        {            
            if(payload == null)
            {
               payload = this.Structure.Members.Where(m => m.ModelShape.IsEventStream).FirstOrDefault();
               //if payload is still null after we search for a member that is of eventStream then the operation is not modeled correctly

               if(payload == null)
                    throw new InvalidOperationException("An eventstream operation's response must have at least one member that is marked with the eventStream trait");
            }

            
            #line default
            #line hidden
            
            #line 55 "CborResponseUnmarshaller.tt"
            this.Write("            response.");
            
            #line default
            #line hidden
            
            #line 55 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payload.PropertyName));
            
            #line default
            #line hidden
            
            #line 55 "CborResponseUnmarshaller.tt"
            this.Write(" = new ");
            
            #line default
            #line hidden
            
            #line 55 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payload.Shape.Name));
            
            #line default
            #line hidden
            
            #line 55 "CborResponseUnmarshaller.tt"
            this.Write("(context.Stream);\n");
            
            #line default
            #line hidden
            
            #line 56 "CborResponseUnmarshaller.tt"

        }
        else if (payloadIsStream)
        {
            if (payload.Shape.IsStreaming)
            {

            
            #line default
            #line hidden
            
            #line 63 "CborResponseUnmarshaller.tt"
            this.Write("            response.");
            
            #line default
            #line hidden
            
            #line 63 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payload.PropertyName));
            
            #line default
            #line hidden
            
            #line 63 "CborResponseUnmarshaller.tt"
            this.Write(" = context.Stream;\n");
            
            #line default
            #line hidden
            
            #line 64 "CborResponseUnmarshaller.tt"

            }
            else if (payload.ModelShape.IsString)
            {

            
            #line default
            #line hidden
            
            #line 69 "CborResponseUnmarshaller.tt"
            this.Write("            response.");
            
            #line default
            #line hidden
            
            #line 69 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payload.PropertyName));
            
            #line default
            #line hidden
            
            #line 69 "CborResponseUnmarshaller.tt"
            this.Write(" = context.ReadTextString();\n");
            
            #line default
            #line hidden
            
            #line 70 "CborResponseUnmarshaller.tt"

            }
            else if (payload.ModelShape.IsMemoryStream)
            {

            
            #line default
            #line hidden
            
            #line 75 "CborResponseUnmarshaller.tt"
            this.Write("            response.");
            
            #line default
            #line hidden
            
            #line 75 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payload.PropertyName));
            
            #line default
            #line hidden
            
            #line 75 "CborResponseUnmarshaller.tt"
            this.Write(" = CborMemoryStreamUnmarshaller.Instance.Unmarshall(context);\n");
            
            #line default
            #line hidden
            
            #line 76 "CborResponseUnmarshaller.tt"

            }
            else
            {
                // At this point, all valid configurations have been handled.  Valid use of payload is defined:
                // https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httppayload-trait
                throw new Exception(
                    $"{payload.PropertyName} can not be a Payload as Type {payload.Shape.Type} is not a valid target for the httpPayload trait.  " +
                    "The httpPayload trait can be applied to structure members that target a string, blob, structure, union, document, set, map, or list.");
            }
        }
        else if (unmarshallPayload)
        {

            
            #line default
            #line hidden
            
            #line 90 "CborResponseUnmarshaller.tt"
            this.Write("            var unmarshaller = ");
            
            #line default
            #line hidden
            
            #line 90 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( payload.DetermineTypeUnmarshallerInstantiate() ));
            
            #line default
            #line hidden
            
            #line 90 "CborResponseUnmarshaller.tt"
            this.Write(";\n            response.");
            
            #line default
            #line hidden
            
            #line 91 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payload.PropertyName));
            
            #line default
            #line hidden
            
            #line 91 "CborResponseUnmarshaller.tt"
            this.Write(" = unmarshaller.Unmarshall(context);\n");
            
            #line default
            #line hidden
            
            #line 92 "CborResponseUnmarshaller.tt"

        }
		else if (this.IsWrapped)
		{

            
            #line default
            #line hidden
            
            #line 97 "CborResponseUnmarshaller.tt"
            this.Write("\t\t\tresponse.");
            
            #line default
            #line hidden
            
            #line 97 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.WrappedResultMember));
            
            #line default
            #line hidden
            
            #line 97 "CborResponseUnmarshaller.tt"
            this.Write(" = ");
            
            #line default
            #line hidden
            
            #line 97 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            
            #line 97 "CborResponseUnmarshaller.tt"
            this.Write("Unmarshaller.Instance.Unmarshall(context);\n");
            
            #line default
            #line hidden
            
            #line 98 "CborResponseUnmarshaller.tt"

		}
        else
        {

            
            #line default
            #line hidden
            
            #line 103 "CborResponseUnmarshaller.tt"
            this.Write(@"            context.PeekState(); // ensure the map header is fully buffered
            reader.ReadStartMap();
            while (context.PeekState() != CborReaderState.EndMap)
            {
                string propertyName = reader.ReadTextString();
                switch (propertyName)
                {
");
            
            #line default
            #line hidden
            
            #line 110 "CborResponseUnmarshaller.tt"

        
            foreach (var member in this.Operation.ResponseBodyMembers)
            {

            
            #line default
            #line hidden
            
            #line 115 "CborResponseUnmarshaller.tt"
            this.Write("                    case \"");
            
            #line default
            #line hidden
            
            #line 115 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.MarshallName));
            
            #line default
            #line hidden
            
            #line 115 "CborResponseUnmarshaller.tt"
            this.Write("\":\n                        {\n                            context.AddPathSegment(\"" +
                    "");
            
            #line default
            #line hidden
            
            #line 117 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            
            #line 117 "CborResponseUnmarshaller.tt"
            this.Write("\");\n                            var unmarshaller = ");
            
            #line default
            #line hidden
            
            #line 118 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( member.DetermineTypeUnmarshallerInstantiate() ));
            
            #line default
            #line hidden
            
            #line 118 "CborResponseUnmarshaller.tt"
            this.Write(";\n                            response.");
            
            #line default
            #line hidden
            
            #line 119 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            
            #line 119 "CborResponseUnmarshaller.tt"
            this.Write(" = unmarshaller.Unmarshall(context);\n                            context.PopPathS" +
                    "egment();\n                            break;\n                        }\n");
            
            #line default
            #line hidden
            
            #line 123 "CborResponseUnmarshaller.tt"

            }

            
            #line default
            #line hidden
            
            #line 126 "CborResponseUnmarshaller.tt"
            this.Write("                    default:\n                        context.SkipValue();\n       " +
                    "                 break;\n                }\n            }\n            reader.ReadE" +
                    "ndMap();\n            context.PopPathSegment();\n");
            
            #line default
            #line hidden
            
            #line 133 "CborResponseUnmarshaller.tt"

        }
    }
	ProcessStatusCode();

            
            #line default
            #line hidden
            
            #line 138 "CborResponseUnmarshaller.tt"
            this.Write(@"
            return response;
        }

        /// <summary>
        /// Unmarshaller error response to exception.
        /// </summary>  
        /// <param name=""context""></param>
        /// <param name=""innerException""></param>
        /// <param name=""statusCode""></param>
        /// <returns></returns>
        public override AmazonServiceException UnmarshallException(CborUnmarshallerContext context, Exception innerException, HttpStatusCode statusCode)
        {
            var errorResponse = CborErrorResponseUnmarshaller.GetInstance().Unmarshall(context);
            errorResponse.InnerException = innerException;
            errorResponse.StatusCode = statusCode;

            var responseBodyBytes = context.GetResponseBodyBytes();

            using (var streamCopy = new MemoryStream(responseBodyBytes))
");
            
            #line default
            #line hidden
            
            #line 158 "CborResponseUnmarshaller.tt"

            if  (this.Config.ServiceModel.IsAwsQueryCompatible)
            {

            
            #line default
            #line hidden
            
            #line 162 "CborResponseUnmarshaller.tt"
 // Create a copy of context with headers in the response 


            
            #line default
            #line hidden
            
            #line 165 "CborResponseUnmarshaller.tt"
            this.Write("            using (var contextCopy = new CborUnmarshallerContext(streamCopy, true" +
                    ", context.ResponseData))\n            {\n");
            
            #line default
            #line hidden
            
            #line 167 "CborResponseUnmarshaller.tt"

                GenerateAWSQueryCompatibleBlock();
                foreach (var exception in this.Operation.Exceptions)
    {

            
            #line default
            #line hidden
            
            #line 172 "CborResponseUnmarshaller.tt"
            this.Write("                if (errorTypeName != null && errorTypeName.Equals(\"");
            
            #line default
            #line hidden
            
            #line 172 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exception.ShapeOriginalName ));
            
            #line default
            #line hidden
            
            #line 172 "CborResponseUnmarshaller.tt"
            this.Write("\"))\n                {\n                    return ");
            
            #line default
            #line hidden
            
            #line 174 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exception.Name));
            
            #line default
            #line hidden
            
            #line 174 "CborResponseUnmarshaller.tt"
            this.Write("Unmarshaller.Instance.Unmarshall(contextCopy, errorResponse);\n                }\n");
            
            #line default
            #line hidden
            
            #line 176 "CborResponseUnmarshaller.tt"

    }
            }   
            else
            {

            
            #line default
            #line hidden
            
            #line 182 "CborResponseUnmarshaller.tt"
            this.Write("            using (var contextCopy = new CborUnmarshallerContext(streamCopy, fals" +
                    "e, context.ResponseData))\n            {\n");
            
            #line default
            #line hidden
            
            #line 184 "CborResponseUnmarshaller.tt"

    foreach (var exception in this.Operation.Exceptions)
    {

            
            #line default
            #line hidden
            
            #line 188 "CborResponseUnmarshaller.tt"
            this.Write("                if (errorResponse.Code != null && errorResponse.Code.Equals(\"");
            
            #line default
            #line hidden
            
            #line 188 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exception.ShapeOriginalName ));
            
            #line default
            #line hidden
            
            #line 188 "CborResponseUnmarshaller.tt"
            this.Write("\"))\n                {\n                    return ");
            
            #line default
            #line hidden
            
            #line 190 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exception.Name));
            
            #line default
            #line hidden
            
            #line 190 "CborResponseUnmarshaller.tt"
            this.Write("Unmarshaller.Instance.Unmarshall(contextCopy, errorResponse);\n                }\n");
            
            #line default
            #line hidden
            
            #line 192 "CborResponseUnmarshaller.tt"

    }
            }

            
            #line default
            #line hidden
            
            #line 196 "CborResponseUnmarshaller.tt"
            this.Write("            }\n            return new ");
            
            #line default
            #line hidden
            
            #line 197 "CborResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.BaseException));
            
            #line default
            #line hidden
            
            #line 197 "CborResponseUnmarshaller.tt"
            this.Write("(errorResponse.Message, errorResponse.InnerException, errorResponse.Type, errorRe" +
                    "sponse.Code, errorResponse.RequestId, errorResponse.StatusCode);\n        }\n\n");
            
            #line default
            #line hidden
            
            #line 200 "CborResponseUnmarshaller.tt"

    if (payload != null && payload.Shape.IsStreaming)
    {

            
            #line default
            #line hidden
            
            #line 204 "CborResponseUnmarshaller.tt"
            this.Write(@"        /// <summary>
        /// Overriden to return true indicating the response contains streaming data.
        /// </summary>
        public override bool HasStreamingProperty
        {
            get
            {
                return true;
            }
        }

");
            
            #line default
            #line hidden
            
            #line 215 "CborResponseUnmarshaller.tt"

	}
    this.AddResponseSingletonMethod();

            
            #line default
            #line hidden
            
            #line 219 "CborResponseUnmarshaller.tt"

    if(isEventStreamOutput)
    {

            
            #line default
            #line hidden
            
            #line 223 "CborResponseUnmarshaller.tt"
            this.Write(@"        /// <summary>
        /// Return false for reading the entire response
        /// </summary>
        /// <param name=""response""></param>
        /// <param name=""readEntireResponse""></param>
        /// <returns></returns>
        protected override bool ShouldReadEntireResponse(IWebResponseData response, bool readEntireResponse)
        {
            return false;
        }
        /// <summary>
        /// Specifies that the response should be streamed
        /// </summary>
        public override bool HasStreamingProperty => true;
");
            
            #line default
            #line hidden
            
            #line 237 "CborResponseUnmarshaller.tt"

    }

            
            #line default
            #line hidden
            
            #line 240 "CborResponseUnmarshaller.tt"
            this.Write("    }\n}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
}
