//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClientGenerator.Generators.Marshallers {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class CborStructureUnmarshaller : BaseResponseUnmarshaller {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "CborStructureUnmarshaller.tt"

    AddLicenseHeader();

    AddCommonUsingStatements();

            
            #line default
            #line hidden
            
            #line 11 "CborStructureUnmarshaller.tt"
            this.Write("using System.Formats.Cbor;\nusing Amazon.Extensions.CborProtocol.Internal.Transfor" +
                    "m;\n#pragma warning disable CS0612,CS0618\nnamespace ");
            
            #line default
            #line hidden
            
            #line 14 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Namespace ));
            
            #line default
            #line hidden
            
            #line 14 "CborStructureUnmarshaller.tt"
            this.Write(".Model.Internal.MarshallTransformations\n{\n    /// <summary>\n    /// Response Unma" +
                    "rshaller for ");
            
            #line default
            #line hidden
            
            #line 17 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 17 "CborStructureUnmarshaller.tt"
            this.Write(" Object\n    /// </summary>  \n    public class ");
            
            #line default
            #line hidden
            
            #line 19 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 19 "CborStructureUnmarshaller.tt"
            this.Write("Unmarshaller : ICborUnmarshaller<");
            
            #line default
            #line hidden
            
            #line 19 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 19 "CborStructureUnmarshaller.tt"
            this.Write(@", CborUnmarshallerContext>
    {
        /// <summary>
        /// Unmarshaller the response from the service to the response class.
        /// </summary>  
        /// <param name=""context""></param>
        /// <returns>The unmarshalled object</returns>
        public ");
            
            #line default
            #line hidden
            
            #line 26 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 26 "CborStructureUnmarshaller.tt"
            this.Write(" Unmarshall(CborUnmarshallerContext context)\n        {\n            ");
            
            #line default
            #line hidden
            
            #line 28 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 28 "CborStructureUnmarshaller.tt"
            this.Write(" unmarshalledObject = new ");
            
            #line default
            #line hidden
            
            #line 28 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 28 "CborStructureUnmarshaller.tt"
            this.Write("();\n            if (context.IsEmptyResponse)\n                return null;\n       " +
                    "     var reader = context.Reader;\n");
            
            #line default
            #line hidden
            
            #line 32 "CborStructureUnmarshaller.tt"

    Member eventPayloadMember = this.Structure.GetExplicitEventPayloadMember();
    //HasImplicitEventPayloadMembers means that the structure does not have a member with the EventPayload trait
    if(this.Structure != null && this.Structure.IsEvent && !this.Structure.HasImplicitEventPayloadMembers() && eventPayloadMember != null)
    {
        if(eventPayloadMember.ModelShape.IsString)
        {

            
            #line default
            #line hidden
            
            #line 40 "CborStructureUnmarshaller.tt"
            this.Write("            unmarshalledObject.");
            
            #line default
            #line hidden
            
            #line 40 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(eventPayloadMember.PropertyName));
            
            #line default
            #line hidden
            
            #line 40 "CborStructureUnmarshaller.tt"
            this.Write(" = context.ReadTextString();\n");
            
            #line default
            #line hidden
            
            #line 41 "CborStructureUnmarshaller.tt"

        }

            
            #line default
            #line hidden
            
            #line 44 "CborStructureUnmarshaller.tt"

        else
        {

            
            #line default
            #line hidden
            
            #line 48 "CborStructureUnmarshaller.tt"
            this.Write("            unmarshalledObject.");
            
            #line default
            #line hidden
            
            #line 48 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(eventPayloadMember.PropertyName));
            
            #line default
            #line hidden
            
            #line 48 "CborStructureUnmarshaller.tt"
            this.Write(" = context.ReadByteString();\n");
            
            #line default
            #line hidden
            
            #line 49 "CborStructureUnmarshaller.tt"

        }

            
            #line default
            #line hidden
            
            #line 52 "CborStructureUnmarshaller.tt"

    }

            
            #line default
            #line hidden
            
            #line 55 "CborStructureUnmarshaller.tt"

    if(this.Structure != null && (this.Structure.HasImplicitEventPayloadMembers() || !this.Structure.IsEvent))
    {

            
            #line default
            #line hidden
            
            #line 59 "CborStructureUnmarshaller.tt"
            this.Write(@"            if (context.PeekState() == CborReaderState.Null)
            {
                reader.ReadNull();
                return null;
            }

            reader.ReadStartMap();
            while (context.PeekState() != CborReaderState.EndMap)
            {
                string propertyName = reader.ReadTextString();
                switch (propertyName)
                {
");
            
            #line default
            #line hidden
            
            #line 71 "CborStructureUnmarshaller.tt"

        foreach (var member in this.Structure.Members)
        {

            
            #line default
            #line hidden
            
            #line 75 "CborStructureUnmarshaller.tt"
            this.Write("                    case \"");
            
            #line default
            #line hidden
            
            #line 75 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.MarshallName));
            
            #line default
            #line hidden
            
            #line 75 "CborStructureUnmarshaller.tt"
            this.Write("\":\n                        {\n                            context.AddPathSegment(\"" +
                    "");
            
            #line default
            #line hidden
            
            #line 77 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            
            #line 77 "CborStructureUnmarshaller.tt"
            this.Write("\");\n                            var unmarshaller = ");
            
            #line default
            #line hidden
            
            #line 78 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( member.DetermineTypeUnmarshallerInstantiate() ));
            
            #line default
            #line hidden
            
            #line 78 "CborStructureUnmarshaller.tt"
            this.Write(";\n                            unmarshalledObject.");
            
            #line default
            #line hidden
            
            #line 79 "CborStructureUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            
            #line 79 "CborStructureUnmarshaller.tt"
            this.Write(" = unmarshaller.Unmarshall(context);\n                            context.PopPathS" +
                    "egment();\n                            break;\n                        }\n");
            
            #line default
            #line hidden
            
            #line 83 "CborStructureUnmarshaller.tt"

        }

            
            #line default
            #line hidden
            
            #line 86 "CborStructureUnmarshaller.tt"
            this.Write("                    default:\n                        context.SkipValue();\n       " +
                    "                 break;\n                }\n            }\n            reader.ReadE" +
                    "ndMap();\n");
            
            #line default
            #line hidden
            
            #line 92 "CborStructureUnmarshaller.tt"

    }

            
            #line default
            #line hidden
            
            #line 95 "CborStructureUnmarshaller.tt"
            this.Write("            return unmarshalledObject;\n        }\n\n\n");
            
            #line default
            #line hidden
            
            #line 99 "CborStructureUnmarshaller.tt"

    this.AddStructureSingletonMethod();

            
            #line default
            #line hidden
            
            #line 102 "CborStructureUnmarshaller.tt"
            this.Write("    }\n}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
}
