//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClientGenerator.Generators.Marshallers {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class CborExceptionUnmarshaller : BaseResponseUnmarshaller {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "CborExceptionUnmarshaller.tt"

    AddLicenseHeader();

    AddCommonUsingStatements();

            
            #line default
            #line hidden
            
            #line 11 "CborExceptionUnmarshaller.tt"
            this.Write("using Amazon.Util;\nusing System.Formats.Cbor;\nusing Amazon.Extensions.CborProtoco" +
                    "l.Internal.Transform;\n#pragma warning disable CS0612,CS0618\nnamespace ");
            
            #line default
            #line hidden
            
            #line 15 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Namespace ));
            
            #line default
            #line hidden
            
            #line 15 "CborExceptionUnmarshaller.tt"
            this.Write(".Model.Internal.MarshallTransformations\n{\n    /// <summary>\n    /// Response Unma" +
                    "rshaller for ");
            
            #line default
            #line hidden
            
            #line 18 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 18 "CborExceptionUnmarshaller.tt"
            this.Write(" Object\n    /// </summary>  \n    public class ");
            
            #line default
            #line hidden
            
            #line 20 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 20 "CborExceptionUnmarshaller.tt"
            this.Write("Unmarshaller : ICborErrorResponseUnmarshaller<");
            
            #line default
            #line hidden
            
            #line 20 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 20 "CborExceptionUnmarshaller.tt"
            this.Write(", CborUnmarshallerContext>\n    {\n        /// <summary>\n        /// Unmarshaller t" +
                    "he response from the service to the response class.\n        /// </summary>  \n   " +
                    "     /// <param name=\"context\"></param>\n        /// <returns></returns>\n        " +
                    "public ");
            
            #line default
            #line hidden
            
            #line 27 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 27 "CborExceptionUnmarshaller.tt"
            this.Write(@" Unmarshall(CborUnmarshallerContext context)
        {
            return this.Unmarshall(context, new Amazon.Runtime.Internal.ErrorResponse());
        }

        /// <summary>
        /// Unmarshaller the response from the service to the response class.
        /// </summary>  
        /// <param name=""context""></param>
        /// <param name=""errorResponse""></param>
        /// <returns></returns>
        public ");
            
            #line default
            #line hidden
            
            #line 38 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 38 "CborExceptionUnmarshaller.tt"
            this.Write(" Unmarshall(CborUnmarshallerContext context, Amazon.Runtime.Internal.ErrorRespons" +
                    "e errorResponse)\n        {\n            ");
            
            #line default
            #line hidden
            
            #line 40 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 40 "CborExceptionUnmarshaller.tt"
            this.Write(" unmarshalledObject = new ");
            
            #line default
            #line hidden
            
            #line 40 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName ));
            
            #line default
            #line hidden
            
            #line 40 "CborExceptionUnmarshaller.tt"
            this.Write("(errorResponse.Message, errorResponse.InnerException,\n                errorRespon" +
                    "se.Type, errorResponse.Code, errorResponse.RequestId, errorResponse.StatusCode);" +
                    "\n            var reader = context.Reader;\n            context.AddPathSegment(\"");
            
            #line default
            #line hidden
            
            #line 43 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName));
            
            #line default
            #line hidden
            
            #line 43 "CborExceptionUnmarshaller.tt"
            this.Write(@""");
            context.PeekState(); // ensure the map header is fully buffered
            reader.ReadStartMap();
            while (context.PeekState() != CborReaderState.EndMap)
            {
                string propertyName = reader.ReadTextString();
                switch (propertyName)
                {
");
            
            #line default
            #line hidden
            
            #line 51 "CborExceptionUnmarshaller.tt"

    if(this.Structure != null)
    {
        foreach (var member in this.Structure.Members)
        {

            
            #line default
            #line hidden
            
            #line 57 "CborExceptionUnmarshaller.tt"
            this.Write("                    case \"");
            
            #line default
            #line hidden
            
            #line 57 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.MarshallName));
            
            #line default
            #line hidden
            
            #line 57 "CborExceptionUnmarshaller.tt"
            this.Write("\":\n                        {\n                            context.AddPathSegment(\"" +
                    "");
            
            #line default
            #line hidden
            
            #line 59 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            
            #line 59 "CborExceptionUnmarshaller.tt"
            this.Write("\");\n                            var unmarshaller = ");
            
            #line default
            #line hidden
            
            #line 60 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( member.DetermineTypeUnmarshallerInstantiate() ));
            
            #line default
            #line hidden
            
            #line 60 "CborExceptionUnmarshaller.tt"
            this.Write(";\n                            unmarshalledObject.");
            
            #line default
            #line hidden
            
            #line 61 "CborExceptionUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            
            #line 61 "CborExceptionUnmarshaller.tt"
            this.Write(" = unmarshaller.Unmarshall(context);\n                            context.PopPathS" +
                    "egment();\n                            break;\n                        }\n");
            
            #line default
            #line hidden
            
            #line 65 "CborExceptionUnmarshaller.tt"

        }
    }

            
            #line default
            #line hidden
            
            #line 69 "CborExceptionUnmarshaller.tt"
            this.Write(@"                    default:
                        context.SkipValue();
                        break;
                }
            }
            reader.ReadEndMap();
            context.PopPathSegment();
          
            return unmarshalledObject;
        }

");
            
            #line default
            #line hidden
            
            #line 80 "CborExceptionUnmarshaller.tt"

    this.AddStructureSingletonMethod();

            
            #line default
            #line hidden
            
            #line 83 "CborExceptionUnmarshaller.tt"
            this.Write("    }\n}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
}
