<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docfx.App" Version="2.78.5" />
    <PackageReference Include="Docfx.Build" Version="2.78.5" />
    <PackageReference Include="Docfx.Dotnet" Version="2.78.5" />
    <PackageReference Include="YamlDotNet" Version="17.1.0" />
  </ItemGroup>

</Project>
